#!/bin/bash

# Remove all the files and directories used by USB emulation and stop it
echo "" > /config/usb_gadget/gadget/UDC
rm /config/usb_gadget/gadget/configs/c.1/*0
rmdir /config/usb_gadget/gadget/configs/c.1/strings/0x409
rmdir /config/usb_gadget/gadget/configs/c.1
rmdir /config/usb_gadget/gadget/functions/*
rmdir /config/usb_gadget/gadget/strings/0x409
rmdir /config/usb_gadget/gadget
rmmod usb_f_ecm usb_f_hid usb_f_mass_storage libcomposite
umount /config
