#!/bin/bash

set_up_overlay() {
  # BBB mounts the system as read-only but we need to be able to make changes
  # to /var so mount an overlay to it using tmpfs. This means that /var becomes
  # writable and any changes to /var will be made only to RAM and when BBB is
  # rebooted everything will be reseted.
  echo "Setup overlay"
  mkdir /ramdisk/upper
  mkdir /ramdisk/work
  mount -t overlay -o lowerdir=/_var,upperdir=/ramdisk/upper,workdir=/ramdisk/work overlay /var
}

set_up_system() {
  echo "Setup system"
  touch /var/lib/misc/dnsmasq.leases
  systemctl restart dnsmasq
  systemctl restart ssh
  chmod 777 /var/run/screen
  iptables-restore < /etc/iptables.rules
  dmesg -n 1
}

set_up_overlay
set_up_system
echo "Done"